# Generated by Django 6.0.3 on 2026-03-26 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_product_model_3d_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='video_360',
            field=models.FileField(blank=True, null=True, upload_to='videos_360/'),
        ),
    ]
